spring.application.name=event-management
spring.datasource.url=jdbc:mysql://localhost:3306/event_management
spring.datasource.username=root
spring.datasource.password=Charan123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sundarts.1971@gmail.com
spring.mail.password=kekfkjvplnavagxo

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

logging.level.org.springframework.security=DEBUG
logging.level.root=INFO
logging.level.com.event.event_management=DEBUG

logging.file.name=logs/event-management.log

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%level] %logger - %msg%n

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

management.info.env.enabled=true

info.app.name=Hackathon Management System
info.app.version=1.0
info.app.description=Event Management REST API
info.app.developer=GS Shanjaiy Samarjith & Sri Charan

# Cloudinary Configuration
cloudinary.cloud_name=Event-Management
cloudinary.api_key=661227816546255
cloudinary.api_secret=pxnCKdYy3ctKY3-kPvGXb9CBfik